### ISSUE TITLE
Truncate filter acting strange when preserving words and last word is quite long

### ISSUE THREAD

**Issue by dritter** [twigphp/Twig-extensions#129]
Hi!

The truncate filter is behaving strange, when preserve words is true, and the last word is quite long.

Example:
`{{ "Tests are uberawesomesuper!" | truncate(11, true, '..') }}`
gives `Tests are uberawesomesuper!`. I expected it to be `Tests are..`.

**Comment by henrikbjorn** [comment]
Isnt this implied in the signature, it will truncate, but preserve words and cut after the limit have been reached?

**Comment by foundryspatial-duncan** [comment]
I think it makes a lot more sense to drop the last word if the cut takes place mid-word. The resulting string shouldn't ever be longer than `limit` characters long. (plus the length of the third parameter `separator`, I guess).
Otherwise, if you want to preserve full words, this filter isn't very useful because the truncated string could theoretically be any length.

**Comment by fabpot** [comment]
I'm closing this issue as we now have native support (including proper Unicode support) in the string Twig extension: see https://twig.symfony.com/u
