### ISSUE TITLE
I18n: Option to specify alternatives for gettext / ngettext (extension config?)

### ISSUE THREAD

**Issue by rubenvincenten** [twigphp/Twig-extensions#152]
As explained by me on https://github.com/oscarotero/Gettext/issues/82#issuecomment-144802849:

> I don't want to rely on the php gettext extension.
> [...]
> However the problem is that `Twig_Extensions_Extension_I18n` compiles twig nodes (trans, plural, notes) to use internal php gettext functions(`gettext` and `ngettext`), making `Gettext\Translator` unusable because `Gettext\Translator::dpgettext` is never being called inside Twig templates.
>
> See [I18n.php](https://github.com/twigphp/Twig-extensions/blame/a155ec01555ffa3aab3e7e042d55aab549c83b75/lib/Twig/Extensions/Extension/I18n.php#L31) and [Trans.php](https://github.com/twigphp/Twig-extensions/blame/a155ec01555ffa3aab3e7e042d55aab549c83b75/lib/Twig/Extensions/Node/Trans.php#L42)

FYI, Gettext/Gettext functions are located here:

https://github.com/oscarotero/Gettext/blob/master/src/translator_functions.php

**Comment by hmpf** [comment]
I want to use Twig_Extensions_Extension_I18n with [oscarotero/Gettext ](https://github.com/oscarotero/Gettext) as well. With pull-request #166 I can easily switch between using gettext and oscarotero/Gettext depending on whether the first exists and works, without forking Twig_Extensions_Extension_I18n. Only Twig_TokenParser_Trans and and Twig_Node_Trans need to be changed for our needs though.

**Comment by jaimeperez** [comment]
This needs to be fixed. Being restricted to PHP's gettext extension is a show-stopper for anyone taking translations seriously, not only because the gettext extension is not thread-safe, but also because it requires you to install all the locales you may need on the server, and that's a huge issue when you don't even have access to the server.

So basically there should be a way to specify which functions you want to use for translations, provided they have the same signature as the original `gettext()` and `ngettext()` functions.

Since this repository looks a bit unmaintained, I've just created [an extension](https://github.com/jaimeperez/twig-configurable-i18n) on top of this that solves the problem for the current version and hopefully also for future updates, if any. Using it is extremely simple, it does **not** require modifications to the templates, and just a minimal modification to the script loading and displaying them.

**Comment by rubenvincenten** [comment]
[offtopic, alternative] If you use symfony or Silex, it is also possible to use symfony/framework-bundle(for extracting), symfony/twig-bundle and symfony/translation.

**Comment by fabpot** [comment]
see #193
