### ISSUE TITLE
Variables in translation not escaped?

### ISSUE THREAD

**Issue by ovidiu** [twigphp/Twig-extensions#241]
This template pops the alert in the second paragraph:

```twig
{% set some_var = "<script>alert('Hello from XSS')</script>" %}

<p>Variable: {{ some_var }}</p>

{% trans %}
    <p>Variable: {{ some_var }}</p>
{% endtrans %}
```
I don't know if it's intended or not, but it surprised me.

* `twig/extensions` v1.5.4
* `twig/twig` v2.7.4
* PHP 7.3.3

**Comment by stof** [comment]
Well, the thing is, this `{{ some_var }}` is not actually handled by Twig, but by the translation layer (as the string being displayed is *not* `<p>Variable: {{ some_var }}</p>` but a translation for it).

IMO, that's the big drawback of the tag-based API of translations in Twig-extensions and in Symfony (and the reason why I always used the filter-based API in Symfony, but it is not available in Twig-extensions).

**Comment by ovidiu** [comment]
Can't a visitor be provided by the extension to escape those values if the regular core extension escaper doesn't see them? Just thinking aloud here, I have zero experience with the codebase.

Or else, if it can't be done, maybe a big fat warning in the documentation would be in order. As a user of the library I find it scary that the first `<p>` is safe and the second `<p>` isn't, when the lines are identical.

**Comment by stof** [comment]
Well, anything inside the `{% trans %}` tag is passed to the translator (gettext in Twig-extensions), which then returns a different string, which is considered safe by the auto-escaper (otherwise, you could not use a `<p>` tag there). But as I said, the inclusion of `some_var` in the translated message is not performed by Twig itself, and so there is no escaping happening automatically here.

@fabpot should Twig-extensions be updated to provide a filter-based API compatible with the Symfony one too ? Or maybe we should deprecate that extension entirely in favor of a gettext-based implementation of the `Symfony\Contracts\Translation\TranslatorInterface` usable with the Symfony translator extension ?

**Comment by ovidiu** [comment]
It's not the strings passed to or returned by gettext that I'm worried about. At least I have control over those strings.

The problem I have is with the values that are interpolated in it after the translation. Those values could come from an attacker.

**Comment by ovidiu** [comment]
To make it clear: maybe you think I expect `<p>` to become `&lt;p&gt;`. I don't. I expect `<script>` to become `&lt;script&gt;`.

I think my example template may have been a bit confusing. Let me rewrite it:

```twig
{% set some_var = "<script>alert('Hello from XSS')</script>" %}

<p>Variable: {{ some_var }}</p>

<p>
    {% trans %}
        Variable: {{ some_var }}
    {% endtrans %}
</p>
```

**Comment by stof** [comment]
Well, the thing is, there is no simple way to apply autoescaping on the variables being interpolated (as the autoescaping applies only on what gets output, and what gets output is the whole translated message).
Escaping the whole translation would break cases where HTML tags were used in it (your first example).

Anyway, changing the behavior of the existing `{% trans %}` tag would be a BC break.

Note that I don't really care about this BC break myself, as I never use it (I'm using the i18n extension of Symfony instead, which is incompatible with that one as they both define a `trans` tag). But that would not be easy to migrate in the ecosystem (there is no way we can provide a deprecation layer there for the behavior change AFAICT).

**Comment by ovidiu** [comment]
Currently the output is:

```php
        echo strtr(gettext("Variable: %some_var%"), array("%some_var%" =>         // line 7
($context["some_var"] ?? null), ));
```

I think it should be:

```php
        echo strtr(gettext("Variable: %some_var%"), array("%some_var%" =>         // line 7
twig_escape_filter($this->env, ($context["some_var"] ?? null), "html", null, true), ));
```

Subject to the current escape strategy, of course…

**Comment by stof** [comment]
But that would require reimplement the whole autoescaping system inside the compilation of this node. Due to the magic being done to handle the vars, there is *no* way to expose them to the autoescaping.

**Comment by ovidiu** [comment]
That node taken in isolation is not aware of the current escaping strategy, right? So I'm not sure it can all be done inside its compile method.

**Comment by twoixter** [comment]
Hi @ovidiu and @stof !! I was reading this thread and I wanted to comment based on the work I did in my PR #176 

Variables inside `Trans` nodes does indeed get auto-escaped! There is a `EscaperNodeVisitor` node visitor that correctly wraps `Twig_Node_Print` nodes (those are the node class that variables get parsed into) with the global `escape` strategy. The problem is that the `Twig_Extensions_Node_Trans` class does a poor job of using variables like that. See **line 139** of `lib/Twig/Extensions/Node/Trans.php` (`compileString` method) in which it effectively ignores all `Twig_Node_Expression_Filter` nodes and goes straight to the `NameExpression` to get the variable name. Later in the `compile` method this is the only node that gets compiled, thus ignoring the wrapper filter.

In my PR #176 this is solved if option `complex_vars` is enabled (otherwise it behaves as usual so as not to break BC). This is the code emitted with `complex_vars` enabled without any other additional change:

```
echo strtr(gettext("<p>Variable: %some_var%</p>"), array("%some_var%" => twig_escape_filter($this->env, // line 6
($context["some_var"] ?? null), "html", null, true), ));
```

This is because the `Twig_Node_Print` is wrapped already with the global auto-escape filter.

I agree with @ovidiu comments completely, it is the same use case we are facing. The strings themselves are safe and are handled to the translators, but then the translated string needs to include potentially dangerous data.
